In [1]:
import sys
import os 
import numpy as np
import pandas as pd
import torch

In [2]:
from torch.utils.data import Dataset, DataLoader

        
import sklearn.preprocessing
from sklearn.decomposition import PCA

## def make_dataset_swat

In [3]:
data_path = '../../../DATA/SWaT/SWaT_Physical/'

In [4]:
train_path = data_path + 'SWaT_Dataset_Normal_v0.csv'
test_path = data_path + 'SWaT_Dataset_Attack_v0.csv'

In [5]:
train_data = pd.read_csv(train_path, index_col = 0)
test_data = pd.read_csv(test_path, index_col = 0)

In [9]:
x_col = list(train_data.columns)[:-1]
y_col = list(train_data.columns)[-1]

In [10]:
train_x = train_data[x_col]
test_x = test_data[x_col]

train_y = train_data[y_col]
test_y = test_data[y_col]

In [13]:
train_y[train_y=='Normal'] = 0
train_y[train_y=='Attack'] = 1

test_y[test_y=='Normal'] = 0
test_y[test_y=='Attack'] = 1

/home/mjh319/anaconda3/envs/Latest_tor_py3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/mjh319/anaconda3/envs/Latest_tor_py3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [20]:
train_y.values.shape

(496800,)

In [11]:
np.flip(t,1)

array([[3, 2, 1],
       [5, 4, 3],
       [7, 6, 5]])

In [5]:
t = t[::-1]

In [6]:
t

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [12]:
import torch

In [13]:
t = torch.tensor([[1,2,3], [3,4,5], [5,6,7]])

In [14]:
t

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [15]:
rNpArr = np.flip(t.numpy(),0).copy()

In [16]:
rNpArr

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])