In [1]:
from data_util.main import load_dataset

I0316 12:03:18.876378 140338102654784 file_utils.py:41] PyTorch version 1.4.0 available.


In [2]:
data_path = '../data'

In [3]:
train_x, train_y, val_x, val_y, test_x, test_y = load_dataset(dataset_name = 'cola', data_path = data_path)

loading cola dataset...
preprocess with pretrained bert


I0316 12:03:20.632951 140338102654784 tokenization_utils.py:501] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/junekyu/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
I0316 12:03:23.514066 140338102654784 configuration_utils.py:256] loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/junekyu/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.8f56353af4a709bf5ff0fbc915d8f5b42bfff892cbb6ac98c3c45f481a03c685
I0316 12:03:23.515079 140338102654784 configuration_utils.py:292] Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "do_sample": false,
  "eos_token_ids": null,
  "finetuning_task": null,
  "hidden_act": "gelu"


fine tuning to word dataset with BERT

fine tuning...
  Batch    40  of    268.    Elapsed: 0:00:06.
  Batch    80  of    268.    Elapsed: 0:00:13.
  Batch   120  of    268.    Elapsed: 0:00:19.
  Batch   160  of    268.    Elapsed: 0:00:25.
  Batch   200  of    268.    Elapsed: 0:00:31.
  Batch   240  of    268.    Elapsed: 0:00:37.

  Average training loss: 0.48
  Training epcoh took: 0:00:41

running validation...
  Accuracy: 0.81
  Validation took: 0:00:00

fine tuning to word dataset with BERT

fine tuning...
  Batch    40  of    268.    Elapsed: 0:00:06.
  Batch    80  of    268.    Elapsed: 0:00:12.
  Batch   120  of    268.    Elapsed: 0:00:19.
  Batch   160  of    268.    Elapsed: 0:00:25.
  Batch   200  of    268.    Elapsed: 0:00:31.
  Batch   240  of    268.    Elapsed: 0:00:37.

  Average training loss: 0.30
  Training epcoh took: 0:00:42

running validation...
  Accuracy: 0.82
  Validation took: 0:00:01

fine tuning to word dataset with BERT

fine tuning...
  Batch    40

In [4]:
train_x[0]

tensor([  101,  2256,  2814,  2180,  1005,  1056,  4965,  2023,  4106,  1010,
         2292,  2894,  1996,  2279,  2028,  2057, 16599,  1012,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0])

In [4]:
train_x[0]

array([  101,  2256,  2814,  2180,  1005,  1056,  4965,  2023,  4106,
        1010,  2292,  2894,  1996,  2279,  2028,  2057, 16599,  1012,
         102,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0])

In [5]:
test_x[0]

array([ 101, 8307, 2074, 2187, 1011, 3984, 2040, 1012,  102,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0])

In [3]:
from dataset import *
import config

In [2]:
print(config.MAX_LEN)

64


In [2]:
data_path = './data'
train_x_cola, train_y_cola, val_x_cola, val_y_cola, test_x_cola, test_y_cola = cola_dataset(data_path = data_path)

Tokenizing CoLA train data with bert tokenizer


I0310 21:23:08.548252 140390183376704 tokenization_utils.py:501] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/junekyu/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


Tokenizing CoLA val data with bert tokenizer


I0310 21:23:10.874847 140390183376704 tokenization_utils.py:501] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/junekyu/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


Tokenizing CoLA test data with bert tokenizer


I0310 21:23:11.958747 140390183376704 tokenization_utils.py:501] loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/junekyu/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


In [3]:
train_x_cola[0]

['our',
 'friends',
 'won',
 "'",
 't',
 'buy',
 'this',
 'analysis',
 ',',
 'let',
 'alone',
 'the',
 'next',
 'one',
 'we',
 'propose',
 '.']

In [7]:
from keras_preprocessing.sequence import pad_sequences
import numpy as np

In [9]:
MAX_LEN = 6
input_ids = np.asarray([1, 2, 3])
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", 
                          value=0, truncating="post", padding="post")

print('')

ValueError: `sequences` must be a list of iterables. Found non-iterable: 1

In [7]:
# # Print the original sentence.
# print(' Original: ', train_x_cola[0])

# # Print the sentence split into tokens.
# print('Tokenized: ', tokenizer.tokenize(train_x_cola[0]))

# # Print the sentence mapped to token ids.
# print('Token IDs: ', tokenizer.convert_tokens_to_ids(tokenizer.tokenize(train_x_cola[0])))

 Original:  Our friends won't buy this analysis, let alone the next one we propose.
Tokenized:  ['our', 'friends', 'won', "'", 't', 'buy', 'this', 'analysis', ',', 'let', 'alone', 'the', 'next', 'one', 'we', 'propose', '.']
Token IDs:  [2256, 2814, 2180, 1005, 1056, 4965, 2023, 4106, 1010, 2292, 2894, 1996, 2279, 2028, 2057, 16599, 1012]
