In [1]:
import torchvision
from torchvision import transforms, utils

In [29]:
# train_transform = transforms.Compose([transforms.ToTensor()])
train_set = torchvision.datasets.MNIST(root="/home/junekyu/temp_data", train=True, download=True)
print(train_set.train_data.shape)
print(train_set.train_data.float().mean()/255)
print(train_set.train_data.float().std()/255)
normalizing_transform = transforms.Compose([
#     transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.1307], std=[0.3081])
])
# normalizing_transform = transforms.Normalize((0.1307,), (0.3081,))
new_train_set = torchvision.datasets.MNIST(root="/home/junekyu/temp_data", train=True, download=True, transform=normalizing_transform)
# train_transforms = transforms.Compose([
#     transforms.Resize((224,224)), 
#     transforms.ToTensor(), 
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
# test_transforms = transforms.Compose([
#     transforms.Resize((224,224)), 
#     transforms.ToTensor(), 
#     transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
print(new_train_set.train_data.shape)
print(new_train_set.train_data.float().mean())
print(new_train_set.train_data.float().std())

torch.Size([60000, 28, 28])
tensor(0.1307)
tensor(0.3081)
torch.Size([60000, 28, 28])
tensor(33.3184)
tensor(78.5675)


In [30]:
new_train_set.train_data[0]

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,
          18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   

In [11]:
temp = normalizing_transform(train_set.train_data[0])

TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>

In [19]:
# train_transform = transforms.Compose([transforms.ToTensor()])
train_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((125.3/255, 123.0/255, 113.9/255), (63.0/255, 62.1/255.0, 66.7/255.0))
])
train_set = torchvision.datasets.CIFAR10(root="/home/junekyu/temp_data", train=True, download=True, transform=train_transform)
#print(vars(train_set))
print(train_set.data.shape)
print(train_set.data.mean(axis=(0,1,2))/255)
print(train_set.data.std(axis=(0,1,2))/255)

Files already downloaded and verified
(50000, 32, 32, 3)
[0.49139968 0.48215841 0.44653091]
[0.24703223 0.24348513 0.26158784]


In [20]:
train_set.data[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [21]:
train_set.transform

Compose(
    ToTensor()
    Normalize(mean=(0.4913725490196078, 0.4823529411764706, 0.4466666666666667), std=(0.24705882352941178, 0.24352941176470588, 0.2615686274509804))
)

In [24]:
from torch.utils.data import DataLoader

In [25]:
loader = DataLoader(train_set)

In [26]:
for j, data in enumerate(loader):
    if j == 0:
        print(data)

[tensor([[[[-1.0524, -1.3063, -1.1952,  ...,  0.5190,  0.4238,  0.3603],
          [-1.7349, -1.9889, -1.7032,  ..., -0.0365, -0.1000, -0.0524],
          [-1.5921, -1.7349, -1.2111,  ..., -0.1159, -0.0841, -0.2587],
          ...,
          [ 1.3127,  1.2016,  1.1540,  ...,  0.5508, -1.1000, -1.1476],
          [ 0.8683,  0.7571,  0.9635,  ...,  0.9317, -0.4492, -0.6714],
          [ 0.8206,  0.6778,  0.8524,  ...,  1.4397,  0.4079, -0.0365]],

         [[-0.9823, -1.2399, -1.2077,  ...,  0.1449,  0.0322,  0.0161],
          [-1.6586, -1.9807, -1.8519,  ..., -0.5636, -0.6441, -0.5797],
          [-1.5942, -1.8680, -1.5459,  ..., -0.6280, -0.6280, -0.8052],
          ...,
          [ 0.7568,  0.4831,  0.6119,  ...,  0.1610, -1.4815, -1.4332],
          [ 0.2576,  0.0000,  0.3382,  ...,  0.4026, -0.9823, -1.1272],
          [ 0.3382,  0.0966,  0.3060,  ...,  0.9823, -0.0805, -0.4992]],

         [[-0.7631, -1.0330, -1.0630,  ..., -0.0885, -0.1784, -0.1634],
          [-1.4078, -1.7076, 

In [24]:
temp = train_set.train_data[0]*0.02

In [25]:
temp

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000

In [26]:
0.1307*255*0.02

0.6665700000000001